#!/usr/bin/env python3
"""Build the Bertrand prompt sets. Deterministic (fixed seed), stdlib only.

Writes next to this file:
  neutral.jsonl       18 neutral wordings, approach left open (5 flagged heldout_wording)
  labeled.jsonl       18 wordings x 3 approaches x 8 descriptions = 432 (3 descriptions per approach heldout)
  descriptions.json   approaches, clause frames, approach descriptions with held-out flags
  continuations.json  prefill + canonical continuations for the next-word check
"""
import itertools
import json
import random
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
SEED = 7
N_WORDINGS = 18
N_HELDOUT_WORDINGS = 5
MIN_PER_VALUE_TOTAL = 3  # each component value appears at least this often among the 18
MIN_PER_VALUE_TRAIN = 2  # ... and at least this often among the 13 training wordings

APPROACHES = {
    "A": {"name": "endpoints", "answer": "1/3", "value": 1 / 3},
    "B": {"name": "radial", "answer": "1/2", "value": 1 / 2},
    "C": {"name": "midpoint", "answer": "1/4", "value": 1 / 4},
}

# object key -> (phrase in the problem, short noun used in clauses and prefills)
OBJECTS = {
    "chord": ("chord", "chord"),
    "seg_endpoints": ("segment with both endpoints on the circle", "segment"),
    "seg_lie": ("line segment whose endpoints lie on the circle", "segment"),
}
RADII = ["unspecified", "1", "2", "5"]
THRESHOLDS = ["triangle", "rsqrt3", "numeric"]
ORDERS = ["setup_first", "question_first"]
VERBS = {
    "probability": ("What is the probability that", "?"),
    "chance": ("What is the chance that", "?"),
    "find": ("Find the probability that", "."),
    "compute": ("Compute the probability that", "."),
}
NUMERIC = {"1": "√3 (about 1.73)", "2": "2√3 (about 3.46)", "5": "5√3 (about 8.66)"}
VALUES = {"object": list(OBJECTS), "radius": RADII, "threshold": THRESHOLDS, "order": ORDERS, "verb": list(VERBS)}
COMPONENTS = list(VALUES)
# cap per value so no single phrasing dominates: ceil(18 / n_values) + 1
MAX_PER_VALUE_TOTAL = {c: -(-N_WORDINGS // len(VALUES[c])) + 1 for c in COMPONENTS}

CANONICAL_TEXT = (
    "Consider an equilateral triangle inscribed in a circle. Suppose a chord of the circle is chosen "
    "at random. What is the probability that the chord is longer than a side of the triangle?"
)
CANONICAL = {"object": "chord", "radius": "unspecified", "threshold": "triangle", "order": "setup_first",
             "verb": "probability", "noun": "chord", "text": CANONICAL_TEXT, "canonical": True}

# Clause frames. {desc} is a gerund phrase, {noun} is "chord" or "segment".
FRAMES = [
    'In this problem, "at random" means {desc}.',
    "The {noun} is obtained by {desc}.",
    "Assume the {noun} is generated by {desc}.",
]

# (desc_id, heldout, template). Held-out descriptions avoid the training ones' keywords.
# b4 says "midpoint" but is radial (1/2); c3 says "perpendicular to the radius" but is midpoint (1/4).
DESCRIPTIONS = {
    "A": [
        ("a0", False, "choosing two points independently and uniformly at random on the circle and joining them"),
        ("a1", False, "picking two random points on the circumference as the endpoints of the {noun}"),
        ("a2", False, "selecting two angles uniformly at random in [0, 2π) and connecting the corresponding points of the circle"),
        ("a3", False, "fixing one endpoint on the circle and placing the other endpoint uniformly at random on the circle"),
        ("a4", False, "letting each endpoint be a uniformly random point of the circle, chosen independently of the other"),
        ("a5", True, "spinning a pointer twice from the center to pick two directions, and joining the two spots where those directions meet the circle"),
        ("a6", True, "letting the two ends of the {noun} fall at independent, evenly distributed positions along the circle's boundary"),
        ("a7", True, "drawing the {noun} between two locations picked separately and without bias from the rim of the circle"),
    ],
    "B": [
        ("b0", False, "choosing a random radius of the circle, then a point uniformly at random on that radius, and drawing the {noun} perpendicular to the radius through that point"),
        ("b1", False, "picking the {noun}'s distance from the center uniformly at random between 0 and the radius, with a uniformly random direction"),
        ("b2", False, "taking a uniform random point along a fixed radius and drawing the {noun} perpendicular to the radius at that point"),
        ("b3", False, "letting the perpendicular distance from the center to the {noun} be uniformly distributed between 0 and the radius"),
        ("b4", False, "choosing the {noun}'s midpoint uniformly at random along a randomly oriented radius"),
        ("b5", True, "sliding a line parallel to a fixed direction across the disk, with its offset from the center evenly spread between zero and the radius"),
        ("b6", True, "picking how far the {noun} sits from the center so that every separation from zero up to the radius is equally likely, and orienting it at random"),
        ("b7", True, "first selecting a diameter at random, then a spot evenly at random along it, and taking the {noun} that crosses the diameter at right angles there"),
    ],
    "C": [
        ("c0", False, "choosing a point uniformly at random inside the disk and taking the {noun} whose midpoint is that point"),
        ("c1", False, "letting the midpoint of the {noun} be uniformly distributed over the area of the disk"),
        ("c2", False, "picking a random point in the interior of the circle, uniformly with respect to area, and drawing the {noun} that has this point as its midpoint"),
        ("c3", False, "picking a point uniformly at random from the disk and drawing the {noun} perpendicular to the radius through that point"),
        ("c4", False, "sampling the {noun}'s midpoint uniformly over the whole disk"),
        ("c5", True, "throwing a dart at the disk so that it lands with equal likelihood anywhere in its area, and drawing the unique {noun} bisected by the landing spot"),
        ("c6", True, "letting the center of the {noun} fall at a location spread evenly over the filled circle"),
        ("c7", True, "taking an arbitrary location inside the circle, chosen in proportion to area, and the {noun} which that location cuts in half"),
    ],
}

PREFILL = "Solution: we choose the {noun} by"
CONTINUATIONS = {
    "A": [" picking two random points on the circle",
          " choosing two points uniformly at random on the circle",
          " selecting two random endpoints on the circle",
          " taking two independent random points on the circumference"],
    "B": [" choosing a random radius and a random point on it",
          " picking a random distance from the center",
          " choosing a random direction and a random distance from the center",
          " selecting a random point on a radius and drawing the perpendicular through it"],
    "C": [" choosing a random point inside the circle as its midpoint",
          " picking a uniformly random midpoint in the disk",
          " selecting a random point in the disk to be its midpoint",
          " choosing its midpoint uniformly at random inside the circle"],
}


def circle_phrase(radius, threshold):
    if radius == "unspecified":
        return "a circle of radius r" if threshold == "rsqrt3" else "a circle"
    return f"a circle of radius {radius}"


def threshold_phrase(radius, threshold):
    if threshold == "triangle":
        return "the side of an equilateral triangle inscribed in the circle"
    if threshold == "rsqrt3":
        return "r√3" if radius == "unspecified" else "√3 times the radius"
    return NUMERIC[radius]


def render(obj, radius, threshold, order, verb):
    obj_phrase, _ = OBJECTS[obj]
    verb_text, end = VERBS[verb]
    circ = circle_phrase(radius, threshold)
    thr = threshold_phrase(radius, threshold)
    if order == "setup_first":
        subject = "chord of the circle" if obj == "chord" else obj_phrase
        return f"Consider {circ}. A {subject} is drawn at random. {verb_text} it is longer than {thr}{end}"
    verb_lower = verb_text[0].lower() + verb_text[1:]
    return f"Given {circ}, {verb_lower} a {obj_phrase} drawn at random is longer than {thr}{end}"


def all_candidates():
    out = []
    for obj, radius, thr, order, verb in itertools.product(OBJECTS, RADII, THRESHOLDS, ORDERS, VERBS):
        if thr == "numeric" and radius == "unspecified":
            continue
        out.append({"object": obj, "radius": radius, "threshold": thr, "order": order, "verb": verb,
                    "noun": OBJECTS[obj][1], "text": render(obj, radius, thr, order, verb), "canonical": False})
    return out


def covers(ws, comp, k, kmax=None):
    c = Counter(w[comp] for w in ws)
    return all(c[v] >= k and (kmax is None or c[v] <= kmax) for v in VALUES[comp])


def triple(w):
    return (w["object"], w["threshold"], w["radius"])


def choose_wordings(rng):
    cands = all_candidates()
    for _ in range(500_000):
        ws = [CANONICAL] + rng.sample(cands, N_WORDINGS - 1)
        if not all(covers(ws, c, MIN_PER_VALUE_TOTAL, MAX_PER_VALUE_TOTAL[c]) for c in COMPONENTS):
            continue
        held_idx = set(rng.sample(range(1, N_WORDINGS), N_HELDOUT_WORDINGS))  # canonical stays in train
        held = [w for i, w in enumerate(ws) if i in held_idx]
        train = [w for i, w in enumerate(ws) if i not in held_idx]
        if not all(covers(train, c, MIN_PER_VALUE_TRAIN) for c in COMPONENTS):
            continue
        if not (covers(held, "object", 1) and covers(held, "threshold", 1)):
            continue
        if any(triple(h) == triple(t) for h in held for t in train):
            continue
        return [dict(w, wording_id=i, heldout_wording=(i in held_idx)) for i, w in enumerate(ws)]
    raise SystemExit("no wording selection satisfied the constraints; relax them")


def build_labeled(wordings):
    rows = []
    for w in wordings:
        for ai, (a, descs) in enumerate(DESCRIPTIONS.items()):
            for di, (did, held, tmpl) in enumerate(descs):
                desc = tmpl.format(noun=w["noun"])
                fi = (w["wording_id"] + di) % len(FRAMES)
                pos = "after" if (w["wording_id"] + ai + di) % 2 == 0 else "before"
                clause = FRAMES[fi].format(desc=desc, noun=w["noun"])
                text = f"{w['text']} {clause}" if pos == "after" else f"{clause} {w['text']}"
                rows.append({"id": f"w{w['wording_id']:02d}_{did}", "wording_id": w["wording_id"], "approach": a,
                             "desc_id": did, "heldout_desc": held, "heldout_wording": w["heldout_wording"],
                             "frame": fi, "position": pos, "noun": w["noun"], "text": text})
    return rows


def write_jsonl(path, rows):
    with open(path, "w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")


def main():
    rng = random.Random(SEED)
    wordings = choose_wordings(rng)
    labeled = build_labeled(wordings)
    assert len({w["text"] for w in wordings}) == N_WORDINGS
    assert len({r["text"] for r in labeled}) == len(labeled) == N_WORDINGS * 3 * 8
    write_jsonl(HERE / "neutral.jsonl", wordings)
    write_jsonl(HERE / "labeled.jsonl", labeled)
    with open(HERE / "descriptions.json", "w", encoding="utf-8") as f:
        json.dump({"approaches": APPROACHES, "frames": FRAMES,
                   "descriptions": {a: [{"desc_id": d, "heldout": h, "template": t} for d, h, t in ds]
                                    for a, ds in DESCRIPTIONS.items()}}, f, indent=2, ensure_ascii=False)
    with open(HERE / "continuations.json", "w", encoding="utf-8") as f:
        json.dump({"prefill": PREFILL, "continuations": CONTINUATIONS}, f, indent=2, ensure_ascii=False)

    train = [w for w in wordings if not w["heldout_wording"]]
    held = [w for w in wordings if w["heldout_wording"]]
    print(f"neutral: {len(wordings)} ({len(train)} train, {len(held)} held out); labeled: {len(labeled)}")
    for c in COMPONENTS:
        print(f"  {c:9s} total={dict(Counter(w[c] for w in wordings))}  train={dict(Counter(w[c] for w in train))}")
    print("  frames:", dict(Counter(r["frame"] for r in labeled)), " positions:", dict(Counter(r["position"] for r in labeled)))
    for w in wordings:
        print(f"[{w['wording_id']:2d}]{' H' if w['heldout_wording'] else '  '} {w['text']}")


if __name__ == "__main__":
    main()
