"""Stage 3 summary: results/s3/steer_{tag}.jsonl -> results/s3/summary.md.

Per target: the answered approach for each prompt and alpha, how many answers give the target's number, the share
of answers where a number was found (coherence indicator), mean length, and a few quoted outputs. No thresholds.
"""
from statistics import mean

from common import APPROACHES, APPROACH_LABEL, RESULTS, read_jsonl, utf8_stdout

S3 = RESULTS / "s3"


def md_table(header, rows):
    out = ["| " + " | ".join(str(h) for h in header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    return "\n".join(out + ["| " + " | ".join(str(c) for c in r) + " |" for r in rows])


def clip(text, n):
    return text[:n] + ("…" if len(text) > n else "")


def section(tag, rows):
    meta = rows[0] if rows and rows[0].get("kind") == "meta" else {}
    ans = [r for r in rows if r.get("kind") == "answer"]
    wids = sorted({r["wording_id"] for r in ans})
    alphas = sorted({r["alpha"] for r in ans if r["target"] != "plain"})
    by = {(r["wording_id"], r["target"], r["alpha"]): r for r in ans}
    plain = {w: by.get((w, "plain", 0.0)) for w in wids}
    sep = meta.get("sep", {})
    out = [f"## {tag}", "",
           f"Layer {meta.get('layer')}, {meta.get('direction')} direction, run {meta.get('time')} on {meta.get('device')} "
           f"{str(meta.get('dtype', '')).replace('torch.', '')}, greedy, max_new_tokens {meta.get('max_new_tokens')}. "
           f"alpha is a multiple of the class separation along the direction (" + ", ".join(f"{a}: {v:.1f}" for a, v in sep.items())
           + f"; mean residual norm {meta.get('resid_norm', float('nan')):.0f}).", "",
           "Unsteered greedy answers (plain): " + " ".join(f"{w}:{plain[w]['approach_number']}" if plain[w] else f"{w}:–" for w in wids), ""]
    hook0 = [r for r in ans if r["target"] != "plain" and r["alpha"] == 0 and "matches_plain" in r]
    if hook0:
        out += [f"alpha = 0 through the hook reproduces the plain answer token for token in {sum(r['matches_plain'] for r in hook0)}/{len(hook0)} cases.", ""]

    for t in APPROACHES:
        if not any(r["target"] == t for r in ans):
            continue
        grid = [[w] + [by[(w, t, a)]["approach_number"] if (w, t, a) in by else "–" for a in alphas] for w in wids]
        have = lambda a: [by[(w, t, a)] for w in wids if (w, t, a) in by]
        grid.append(["**answers = target**"] + [f"**{sum(r['approach_number'] == t for r in have(a))}/{len(have(a))}**" for a in alphas])
        grid.append(["number found"] + [f"{sum(r['approach_number'] in ('A', 'B', 'C', 'other') for r in have(a))}/{len(have(a))}" for a in alphas])
        grid.append(["mean tokens"] + [f"{mean(r['n_tokens'] for r in have(a)):.0f}" if have(a) else "–" for a in alphas])
        out += [f"### Target {APPROACH_LABEL[t]}", "", md_table(["wording \\ alpha"] + [f"{a:g}" for a in alphas], grid), ""]

    for t in APPROACHES:
        cands = sorted([r for r in ans if r["target"] == t and r["approach_number"] == t and plain.get(r["wording_id"])
                        and plain[r["wording_id"]]["approach_number"] != t], key=lambda r: (r["alpha"], r["wording_id"]))
        if cands:
            r = cands[0]
            out += [f"#### Example switch to {t}: wording {r['wording_id']}, alpha {r['alpha']:g} "
                    f"(plain answer was {plain[r['wording_id']]['approach_number']})", "", "```", clip(r["answer"], 1200), "```", ""]
    if alphas:
        hi = [r for r in ans if r["target"] != "plain" and r["alpha"] == max(alphas)]
        if hi:
            r = hi[0]
            out += [f"#### Highest alpha, first sample: target {r['target']}, wording {r['wording_id']}, alpha {r['alpha']:g} -> {r['approach_number']}",
                    "", "```", clip(r["answer"], 800), "```", ""]
    return "\n".join(out)


def main():
    utf8_stdout()
    parts = ["# Stage 3 steering sweep", "", "Generated by `s3_summarize.py` from `results/s3/steer_*.jsonl`.", ""]
    for f in sorted(S3.glob("steer_*.jsonl")):
        parts.append(section(f.stem.split("_", 1)[1], read_jsonl(f)))
    text = "\n".join(parts)
    (S3 / "summary.md").write_text(text, encoding="utf-8")
    print(text)


if __name__ == "__main__":
    main()
